language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "esfak47"
    token:
      secure: "beaJM3no947WnDOhtKMRid9JPI+wzmdeGNXDrKetwsJGqyCGdbAq2zObtcntV9vvFiN5fLBIa9AmJ+wevUeMAoIXy58QZiPjCfxc1pUCDBe+cSX71zJ5wcwipsZ86QeMDL3VSEWHjBGbSOaEhQD+MML3wnxS7/iiWZVuHnvNfLc4z0+eYOTlhmsZFcExdWgBkfKBr3X/XTaXXnzWJMX7p8BB1544WiIpxhLKUZoNXFx76OgoIVf3PtmWcjhHnRSi/1eW+zLZHeiEdT2YSbl9tcjcfKnELjk//TZ81InwcFvlUyIbA/G+5v3YHEn9Hlq1MYY4Sy6Y5rVUoDfh3KCBm9Fzg6cV31mZbdoB4Xp0+h4IFVBzJAoR8MYGRNO7MTKRgsmnKv8Xwic8B1JiMiCV46bZnJ2/ItUO2nRFgRU2EmiJVfXHHCV6k4DJ55ecU4oS3BcMykrl7scSuMJHBumlFXIL2Qz/070dr4725qgWGzlFhCjJGhY08ilJqVRFNd5yYZYZIvvz/MCtQ89xCFTUI8RM1SL2JEqXqA1Q9BXAyMqZNnerjj0WTs/euRznaChkNVU0kSAGPIV7s5uiguH2YKwuaoRSipoI2KfXP3mSCCaLnCMNaI/Vbehq9ycYQRk1ZUS2NMjoXk1xlvSMJw6BFYWUrB1lxD1giJskSXAJ+Ps="
before_install:
   - "echo skipped"
install:
  - "echo skipped"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email:
    recipients:
      - esfak47@qq.com