language: java
jdk:
  - openjdk8
before_install:
   - "echo skipped"
install:
  - "echo skipped"
script:
  - mvn install -Dmaven.javadoc.skip=true
notifications:
  email:
    recipients:
      - esfak47@qq.com