language: java
sudo: false
install: true
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: esfak47
    token:
      secure: "e98zCl11jVNxvjtlYHoZJW7dboK1+Zk8lygCBasSWnxfUWxeTQWnWa2eCoCobQNBgX1Bu0raxdEPpkK9ANJ+HuyxuzlMIhYw5KBTFqe+NEe/af/iknM81pHZn0yzcziy3FQFhA107XHy+2XFLC9hqlQVMPJzOX7v2YhejBtjDUpmttTqfCxLKRO4692FK+kXnjlvb3ifBSUQwoBjkPTn2ju/65No19s4o87Y69QGOoZ/aaJB5YQJuES9RaY9xglNiDiHtQWXIBEafSYiDGb5TMjS33yRgG7byQMjyh3Y6W+rekrW+3HVyyU627+oEIM0g7zRLfv5ucZlFNGw/5MnblDzdwbnuJ+q0WT3LjA3M6KF/uDzx/92pdYmGAH7nx95oDxdriS0XICg1m5kw+PKy25cEni5eS7mpMej9h/V66FHwqFp0PIH4ZvXAdDxKVGb6KB8/m1TYpvCn2WM4QhRiVXsR9wv3Gw9QYflZbZJG87/Z7Q5c0BytoJfQzcpVSFOq/R6JsR9h3Ve3G08f6doaPLD3px2zU/BhuhA9iJ5Z9oAMFKpmi47XXXma2rKcTYOzR/DmXbIRH/Yg7XCvqklLETc3Ypve4bBntZBZCa7MT7zKtgjFJDoBOkvC1InL+XoFKFYFwfNIGpQewEmyWJy57qfiTB8OLv7vrFNV3yrUv4="

before_install:
- echo skipped
install:
- echo skipped
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=11fd8c7be579f3ce7a43ea619c6566101eeaed5c3631da5a17ada92e3ba29ead
  email:
    recipients:
    - esfak47@qq.com