language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: esfak47
    token:
      secure: Ni5R/2uHbnFO3HTZA1buSCUn8u9LwjQZ6vaEuZcyAsF049hsQWsBfT+vkl6y24nrU4kTFvLqlfEHRGUU5TMYw7js9D4CoJaZXG2DdzyysvL41scxXZQXCJvSRvwnAwuqHXxtVQa7+9rP6MFuWgfFSl72L/D47cb1d9pn/kq7CRXnLzfQosSUYa3olxPw1zC4xUZg6CKdt092xpACXMoOlpAFpYfF113SfSOb9OMTmU0EQp4fz0EHwaEdZSrGBRhYSpJDrf8K1g+7cdkq17jALNqagoKDHj6ZfoosU7k/TQhCxoQCBSNiyXozfTaMT/KDD5BqYtDHgTS7TPvlRmLsC02YCdSM3AkAST3oKphMvdgsO9PWAJyGHnm2552HVrZg6TK0ed0VCnjj/InZZLjV4PSamg7rZYalTr0w77y+/G7kfvjwDyaFgjgxNPjX6uir6tYuydDWVvIAch0Ukqo6d6AfAUxMHNzJRfhAP72pUKzTDFxULvIAya4Dn0yADEEGLgVtVjOp5hn/Xuo932UQyRmEC8g2k9EudS8MzaXaN5xiBbvYSVUO/pcQiv3xm62wVisIIrshM8IX3H5TCWvhoRgzptn8xUikBYIzpg/G08H82w8NJSwcuLKIZQRKr1UWOiRiSVpVnnV2XNiHb/0IVbYIH1yaUhrP7Dj/oCJwy1c=
before_install:
- echo skipped
install:
- echo skipped
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email:
    recipients:
    - esfak47@qq.com
env:
  global:
  - secure: Ni5R/2uHbnFO3HTZA1buSCUn8u9LwjQZ6vaEuZcyAsF049hsQWsBfT+vkl6y24nrU4kTFvLqlfEHRGUU5TMYw7js9D4CoJaZXG2DdzyysvL41scxXZQXCJvSRvwnAwuqHXxtVQa7+9rP6MFuWgfFSl72L/D47cb1d9pn/kq7CRXnLzfQosSUYa3olxPw1zC4xUZg6CKdt092xpACXMoOlpAFpYfF113SfSOb9OMTmU0EQp4fz0EHwaEdZSrGBRhYSpJDrf8K1g+7cdkq17jALNqagoKDHj6ZfoosU7k/TQhCxoQCBSNiyXozfTaMT/KDD5BqYtDHgTS7TPvlRmLsC02YCdSM3AkAST3oKphMvdgsO9PWAJyGHnm2552HVrZg6TK0ed0VCnjj/InZZLjV4PSamg7rZYalTr0w77y+/G7kfvjwDyaFgjgxNPjX6uir6tYuydDWVvIAch0Ukqo6d6AfAUxMHNzJRfhAP72pUKzTDFxULvIAya4Dn0yADEEGLgVtVjOp5hn/Xuo932UQyRmEC8g2k9EudS8MzaXaN5xiBbvYSVUO/pcQiv3xm62wVisIIrshM8IX3H5TCWvhoRgzptn8xUikBYIzpg/G08H82w8NJSwcuLKIZQRKr1UWOiRiSVpVnnV2XNiHb/0IVbYIH1yaUhrP7Dj/oCJwy1c=
